**PRACTICA CALIFICADA**

In [124]:
#Estos son los paquetes que usamos
import requests
from bs4 import BeautifulSoup as b
import pandas as pd 
import numpy as np
from selenium import webdriver
import re 
from selenium.webdriver.common.action_chains import ActionChains

genes= pd.read_excel("CHGenesOrdenadosConVecinos 2.xlsx",usecols=["Gen Abrev","Category","Name of the gene","Inicio",
                                                                   "Final","RNASeq","Microarray","SAGE"],skiprows=1)

#Solo usaremos 7 filas debido a que nuestras pcs estan demorando en procesar, de todas maneras no influye en los resultados.

genes.head(9)#

,Gen Abrev,Category,Name of the gene,Inicio,Final,RNASeq,Microarray,SAGE
0,TRNAS-GGA,NaN,NaN,32091689,32091761,NaN,NaN,NaN
1,LOC102173449,NaN,NaN,32837131,32838076,NaN,NaN,NaN
2,LOC102169333,NaN,NaN,33089112,33090132,NaN,NaN,NaN
3,LOC108636757,NaN,NaN,33764252,33768221,NaN,NaN,NaN
4,LOC102187712,NaN,NaN,33810174,33811741,NaN,NaN,NaN
5,VGLL3,NaN,NaN,33882149,33934641,NaN,NaN,NaN
6,CHMP2B,NaN,NaN,34199383,34231630,NaN,NaN,NaN

In [125]:
virus_t = genes["Gen Abrev"].tolist()#se crea una variable para extraer la columna de GEN ABREV en una lista
virus_t

['TRNAS-GGA',
 'LOC102173449',
 'LOC102169333',
 'LOC108636757',
 'LOC102187712',
 'VGLL3',
 'CHMP2B']